import type { LeadQualified } from '../types/lead-finder.js';
import { ENV_REQUIREMENTS, getEnv, getEnvOptional, validateEnv } from '../utils/env.js';
import { logger } from '../utils/logger.js';

interface AirtableRecord {
  id: string;
  fields: Record<string, unknown>;
}

interface AirtableField {
  id: string;
  name: string;
  type: string;
  options?: {
    choices?: Array<{
      id?: string;
      name: string;
      color?: string;
    }>;
  };
}

interface AirtableTable {
  id: string;
  name: string;
  fields: AirtableField[];
}

interface AirtableSchemaResponse {
  tables?: AirtableTable[];
}

interface AirtableFieldSpec {
  name: string;
  type: string;
  description?: string;
  options?: Record<string, unknown>;
}

function formatReviewSnippet(review: LeadQualified['reviews'][number]): string {
  const meta = [
    review.author,
    review.rating != null ? `${review.rating.toFixed(1)}/5` : null,
    review.relativeTime
  ].filter(Boolean).join(' · ');

  return meta ? `${meta}\n${review.text}` : review.text;
}

const LEAD_FIELD_SPECS: AirtableFieldSpec[] = [
  { name: 'lead_id', type: 'singleLineText', description: 'Stable technical id generated by lead-finder.' },
  { name: 'business_name', type: 'singleLineText' },
  { name: 'category', type: 'singleLineText' },
  { name: 'city', type: 'singleLineText' },
  { name: 'rating', type: 'number', options: { precision: 1 } },
  { name: 'review_count', type: 'number', options: { precision: 0 } },
  { name: 'maps_url', type: 'url' },
  { name: 'website_url', type: 'url' },
  {
    name: 'website_status',
    type: 'singleSelect',
    options: {
      choices: [
        { name: 'no_domain', color: 'greenLight2' },
        { name: 'social_only', color: 'yellowLight2' },
        { name: 'has_domain', color: 'redLight2' },
        { name: 'chain_or_franchise', color: 'grayLight2' },
        { name: 'closed_or_invalid', color: 'grayLight2' }
      ]
    }
  },
  { name: 'social_links', type: 'multilineText' },
  { name: 'fallback_channels', type: 'multilineText' },
  { name: 'contact_email', type: 'email' },
  {
    name: 'contact_channel',
    type: 'singleSelect',
    options: {
      choices: [
        { name: 'email', color: 'greenLight2' },
        { name: 'phone', color: 'blueLight2' },
        { name: 'website', color: 'cyanLight2' },
        { name: 'social', color: 'yellowLight2' },
        { name: 'none', color: 'redLight2' }
      ]
    }
  },
  {
    name: 'contact_confidence',
    type: 'singleSelect',
    options: {
      choices: [
        { name: 'high', color: 'greenLight2' },
        { name: 'medium', color: 'yellowLight2' },
        { name: 'low', color: 'orangeLight2' },
        { name: 'none', color: 'redLight2' }
      ]
    }
  },
  { name: 'lead_score', type: 'number', options: { precision: 0 } },
  { name: 'image_count', type: 'number', options: { precision: 0 } },
  { name: 'review_snippets', type: 'multilineText' },
  { name: 'detail_highlights', type: 'multilineText' },
  { name: 'rich_data_json', type: 'multilineText' },
  { name: 'preview_url', type: 'url' },
  {
    name: 'lead_status',
    type: 'singleSelect',
    options: {
      choices: [
        { name: 'new', color: 'grayLight2' },
        { name: 'qualified', color: 'blueLight2' },
        { name: 'draft_ready', color: 'purpleLight2' },
        { name: 'approved', color: 'greenLight2' },
        { name: 'contacted', color: 'cyanLight2' },
        { name: 'rejected', color: 'redLight2' }
      ]
    }
  },
  { name: 'last_action_at', type: 'singleLineText' },
  { name: 'notes', type: 'multilineText' }
];

const LOGICAL_FIELD_ALIASES = new Map([
  ['business_name', 'name'],
  ['status', 'lead_status'],
  ['notes', 'notes']
]);

function getBaseUrl(): string {
  validateEnv(ENV_REQUIREMENTS.airtable);
  const baseId = getEnv('airtableBaseId');
  const tableName = encodeURIComponent(getEnvOptional('airtableTableName', 'Leads'));
  return `https://api.airtable.com/v0/${baseId}/${tableName}`;
}

function getMetadataBaseUrl(): string {
  validateEnv(ENV_REQUIREMENTS.airtable);
  return `https://api.airtable.com/v0/meta/bases/${getEnv('airtableBaseId')}`;
}

function getHeaders(): Record<string, string> {
  return {
    Authorization: `Bearer ${getEnv('airtableApiKey')}`,
    'Content-Type': 'application/json'
  };
}

async function getConfiguredTable(): Promise<AirtableTable> {
  const response = await fetch(`${getMetadataBaseUrl()}/tables`, { headers: getHeaders() });
  if (!response.ok) {
    throw new Error(`Airtable schema lookup failed: ${response.status} ${response.statusText} — ${await response.text()}`);
  }

  const payload = (await response.json()) as AirtableSchemaResponse;
  const configured = getEnvOptional('airtableTableName', 'Leads');
  const table = payload.tables?.find(candidate => candidate.id === configured || candidate.name === configured);
  if (!table) {
    throw new Error(`Table Airtable introuvable: ${configured}`);
  }

  return table;
}

function buildCanonicalFieldMap(table: AirtableTable): Map<string, string> {
  return new Map(table.fields.map(field => [field.name.toLowerCase(), field.name]));
}

function canonicalField(canonical: Map<string, string>, logicalName: string): string {
  const lowerName = logicalName.toLowerCase();
  const alias = LOGICAL_FIELD_ALIASES.get(lowerName);
  return (alias ? canonical.get(alias) : undefined) ?? canonical.get(lowerName) ?? logicalName;
}

async function mapFieldsToAirtableNames(fields: Record<string, unknown>): Promise<Record<string, unknown>> {
  const table = await getConfiguredTable();
  const canonical = buildCanonicalFieldMap(table);
  const mapped: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(fields)) {
    mapped[canonicalField(canonical, key)] = value;
  }

  return mapped;
}

function toLogicalFields(lead: LeadQualified): Record<string, unknown> {
  const reviews = lead.reviews ?? [];
  const images = lead.images ?? [];
  const details = lead.businessDetails ?? {
    priceRange: null,
    serviceOptions: [],
    diningOptions: [],
    offerings: [],
    atmosphere: [],
    accessibility: [],
    planning: [],
    rawAttributes: []
  };

  return {
    lead_id: lead.leadId,
    business_name: lead.businessName,
    category: lead.category ?? '',
    city: lead.city,
    rating: lead.rating ?? null,
    review_count: lead.reviewCount ?? null,
    maps_url: lead.source.mapsUrl,
    website_url: lead.websiteUrl ?? '',
    website_status: lead.websiteStatus,
    social_links: lead.socialLinks.join('\n'),
    fallback_channels: lead.contact.fallbackChannels.join('\n'),
    contact_email: lead.contact.email ?? '',
    contact_channel: lead.contact.channel,
    contact_confidence: lead.contact.confidence,
    lead_score: lead.score.total,
    image_count: lead.imageUrls.length,
    review_snippets: reviews.map(formatReviewSnippet).join('\n\n'),
    detail_highlights: [
      details.priceRange ? `Prix: ${details.priceRange}` : null,
      ...details.serviceOptions,
      ...details.diningOptions,
      ...details.offerings,
      ...details.atmosphere,
      ...details.accessibility,
      ...details.planning
    ].filter(Boolean).join('\n'),
    rich_data_json: JSON.stringify({
      images,
      reviews,
      businessDetails: details
    }, null, 2),
    preview_url: lead.previewUrl ?? '',
    status: lead.status,
    last_action_at: lead.lastActionAt ?? '',
    notes: lead.notes
  };
}

async function findRecordByLeadId(leadId: string): Promise<AirtableRecord | null> {
  const table = await getConfiguredTable();
  const canonical = buildCanonicalFieldMap(table);
  const leadIdField = canonical.get('lead_id');
  if (!leadIdField) {
    throw new Error('Champ Airtable manquant: lead_id. Lancez npm run lead:airtable:bootstrap.');
  }

  const url = `${getBaseUrl()}?filterByFormula=${encodeURIComponent(`{${leadIdField}}='${leadId}'`)}`;
  const response = await fetch(url, { headers: getHeaders() });
  if (!response.ok) {
    throw new Error(`Airtable lookup failed: ${response.status} ${response.statusText} — ${await response.text()}`);
  }
  const payload = (await response.json()) as { records?: AirtableRecord[] };
  return payload.records?.[0] ?? null;
}

export async function syncLeadsToAirtable(leads: LeadQualified[]): Promise<void> {
  logger.info(`📒 Sync Airtable: ${leads.length} leads`);

  for (const lead of leads) {
    const existing = await findRecordByLeadId(lead.leadId);
    const fields = await mapFieldsToAirtableNames(toLogicalFields(lead));

    const response = await fetch(existing ? `${getBaseUrl()}/${existing.id}` : getBaseUrl(), {
      method: existing ? 'PATCH' : 'POST',
      headers: getHeaders(),
      body: JSON.stringify({ fields })
    });

    if (!response.ok) {
      throw new Error(
        `Airtable sync failed for ${lead.businessName}: ${response.status} ${response.statusText} — ${await response.text()}`
      );
    }
  }
}

export async function listApprovedAirtableLeads(): Promise<AirtableRecord[]> {
  const table = await getConfiguredTable();
  const canonical = buildCanonicalFieldMap(table);
  const statusField = canonicalField(canonical, 'status');
  const contactEmailField = canonicalField(canonical, 'contact_email');
  const formula = `AND({${statusField}}='approved', {${contactEmailField}}!='')`;
  const url = `${getBaseUrl()}?filterByFormula=${encodeURIComponent(formula)}`;
  const response = await fetch(url, { headers: getHeaders() });
  if (!response.ok) {
    throw new Error(`Airtable approved list failed: ${response.status} ${response.statusText} — ${await response.text()}`);
  }
  const payload = (await response.json()) as { records?: AirtableRecord[] };
  return payload.records ?? [];
}

export async function updateAirtableAfterPreview(leadId: string, previewUrl: string): Promise<void> {
  const record = await findRecordByLeadId(leadId);
  if (!record) return;

  const response = await fetch(`${getBaseUrl()}/${record.id}`, {
    method: 'PATCH',
    headers: getHeaders(),
    body: JSON.stringify({ fields: await mapFieldsToAirtableNames({ preview_url: previewUrl, status: 'draft_ready' }) })
  });

  if (!response.ok) {
    throw new Error(`Airtable preview update failed: ${response.status} ${response.statusText} — ${await response.text()}`);
  }
}

export async function markAirtableLeadContacted(
  recordId: string,
  sentAt: string,
  notes: string
): Promise<void> {
  const response = await fetch(`${getBaseUrl()}/${recordId}`, {
    method: 'PATCH',
    headers: getHeaders(),
    body: JSON.stringify({ fields: await mapFieldsToAirtableNames({ status: 'contacted', last_action_at: sentAt, notes }) })
  });

  if (!response.ok) {
    throw new Error(`Airtable outreach update failed: ${response.status} ${response.statusText} — ${await response.text()}`);
  }
}

export async function clearAirtableLeads(): Promise<number> {
  const response = await fetch(getBaseUrl(), { headers: getHeaders() });
  if (!response.ok) {
    throw new Error(`Airtable clear list failed: ${response.status} ${response.statusText} — ${await response.text()}`);
  }

  const payload = (await response.json()) as { records?: AirtableRecord[] };
  const records = payload.records ?? [];
  if (records.length === 0) return 0;

  for (let index = 0; index < records.length; index += 10) {
    const chunk = records.slice(index, index + 10);
    const query = chunk.map(record => `records[]=${encodeURIComponent(record.id)}`).join('&');
    const deleteResponse = await fetch(`${getBaseUrl()}?${query}`, {
      method: 'DELETE',
      headers: {
        Authorization: `Bearer ${getEnv('airtableApiKey')}`
      }
    });

    if (!deleteResponse.ok) {
      throw new Error(`Airtable clear failed: ${deleteResponse.status} ${deleteResponse.statusText} — ${await deleteResponse.text()}`);
    }
  }

  return records.length;
}

export async function bootstrapAirtableLeadSchema(): Promise<void> {
  const table = await getConfiguredTable();
  const existing = buildCanonicalFieldMap(table);
  const missing = LEAD_FIELD_SPECS.filter(spec => {
    const lowerName = spec.name.toLowerCase();
    const alias = LOGICAL_FIELD_ALIASES.get(lowerName);
    return !existing.has(lowerName) && !(alias && existing.has(alias));
  });

  if (missing.length === 0) {
    logger.success('Schéma Airtable déjà prêt');
  } else {
    logger.info(`🧱 Création de ${missing.length} champs Airtable dans ${table.name}`);

    for (const spec of missing) {
      const response = await fetch(`${getMetadataBaseUrl()}/tables/${table.id}/fields`, {
        method: 'POST',
        headers: getHeaders(),
        body: JSON.stringify(spec)
      });

      if (!response.ok) {
        throw new Error(
          `Création du champ Airtable "${spec.name}" échouée: ${response.status} ${response.statusText} — ${await response.text()}`
        );
      }

      logger.success(`  Champ créé: ${spec.name}`);
    }
  }

  await ensureSingleSelectChoices('lead_status');
  await ensureSingleSelectChoices('website_status');
  await ensureSingleSelectChoices('contact_channel');
  await ensureSingleSelectChoices('contact_confidence');
}

async function ensureSingleSelectChoices(fieldName: string): Promise<void> {
  const table = await getConfiguredTable();
  const field = table.fields.find(candidate => candidate.name === fieldName);
  const spec = LEAD_FIELD_SPECS.find(candidate => candidate.name === fieldName);
  const desiredChoices = spec?.options?.choices;

  if (!field || field.type !== 'singleSelect' || !Array.isArray(desiredChoices)) return;

  const existingChoices = field.options?.choices ?? [];
  const missingChoices = desiredChoices.filter(choice =>
    !existingChoices.some(existing => existing.name === choice.name)
  );
  if (missingChoices.length === 0) return;

  const mergedChoices = [...existingChoices, ...missingChoices];
  const response = await fetch(`${getMetadataBaseUrl()}/tables/${table.id}/fields/${field.id}`, {
    method: 'PATCH',
    headers: getHeaders(),
    body: JSON.stringify({
      options: {
        choices: mergedChoices.map(choice => ({
          name: choice.name,
          color: choice.color ?? 'blueLight2'
        }))
      }
    })
  });

  if (!response.ok) {
    throw new Error(
      `Mise à jour des options Airtable "${fieldName}" échouée: ${response.status} ${response.statusText} — ${await response.text()}`
    );
  }

  logger.success(`  Options mises à jour: ${fieldName} (+${missingChoices.length})`);
}
